version=1.0.0
application.name=World Repair Studio
application.bundleId=io.github.swbarron.worldrepairstudio
application.url=https://github.com/swbarron/world-repair-studio
application.author=Samuel Barron; based on MCA Selector by Querz
application.copyright=© 2018 - 2026 Querz; modifications © 2026 Samuel Barron
